### ISSUE TITLE
Add CLA

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community-Module#3]
https://cla-assistant.io/

CLA is something like transferring ownership of code, which protects you from any possible future copyright claim by a contributor. It also allows you to change license without having to ask each contributor for permission.

Many open source projects use CLA, for example RocketMod added it too on my suggestion.

After adding CLA, only accept pull requests which are CLA-signed.

**Comment by SDGNelson** [comment]
Thanks for the information! This has now been configured for the repo.
