### ISSUE TITLE
Audio Streaming

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community-Module#4]
https://github.com/Trojaner25/Unturned-3.x-Community-Module/tree/feature-audiostreaming
(Will do PR as soon as the restructure PR gets merged)

Changed files without the restructure commits are visible here: https://github.com/Trojaner25/Unturned-3.x-Community-Module/compare/mod...Trojaner25:feature-audiostreaming

Unity can stream / play wav and ogg on PC. More information here: https://docs.unity3d.com/353/Documentation/Manual/AudioFiles.html

Requested from RoyIL:
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/185

Added SteamCalls:
```csharp
PlayAudio(string url, int playbackId, bool isStream, bool autoPlay)
SetAudioVolume(int playbackId, float volume)
AttachAudioToPlayer(int playbackId, CSteamID target)
AttachAudioToVehicle(int playbackId, uint vehId)
DeattachAudio(int playbackId)
SetAudioPosition(int playbackId, Vector3 pos)
SetAudioMaxDistance(int playbackId, float maxDistance)
SetAudioMinDistance(int playbackId, float minDistance)
ResumeAudio(int playbackId)
PauseAudio(int playbackId)
RemoveAudio(int playbackId)
```

Currently max. 5 streams can play at the same time.
When leaving the server, everything audio-related gets disposed and destroyed.

Example usage scenarios:
```
* /radio which streams some radio station
* Adding custom sound to players, vehicles, buildings etc... 
* Vehicles with real radio
* Custom music
* ???
...
etc
```

Compared to Workshop this is much more flexible (only downloaded on-demand, can be modified / updated easily, easier to setup etc) and allows *streaming* endless audio. Also options like `minDistance`, `maxDistance`, `volume`, `position`, `parent` can be set dynamically.

TODO:
* [x] Check if channels match on server and client (they do, ch# 2)
* [x] Check if streaming works at all
* [ ] Check if other channels are still working (maybe the new channel messed up player channels?)
* [ ] Make demo plugin
* [ ] Check if works when autoStart is false
* [ ] Test all new SteamCalls
* [ ] Check what happens when download fails
* [ ] Adjust Interval
* [ ] Cache downloadable sound files (`isStream == false`) instead of streaming them (so it doesn't have to redownload them every time)

Any thoughts on this?

**Comment by huiseDT** [comment]
Great!

**Comment by Trojaner25** [comment]
I don't know if it's worth continuing this since the other PR hasn't been merged in 16 days and Nelson didn't comment on this one yet...

**Comment by Trojaner25** [comment]
Created PR: #5
